#key_export.py
"""This is for exporting keys and metadata in multiple formats like PEM, JSON, JWK
, Binary, QR, SSH and PKCS8. ALL COMPLETELY SELF WRITTEN BTW"""
import base64
import json
import struct
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict
from entropygarden.key_derive import compute_checksum
from entropygarden.cli_output import log


def to_pem(key:bytes, label: str, meta: Dict) -> str:
    """Format key as something like a PEM block with metadata comments"""
    b64 = base64.b64encode(key).decode()
    cs = compute_checksum(key)
    lines = [f"-----BEGIN {label.upper()}-----"]
    lines.append(f"# Generated by EntropyGarden on {meta.get('created_at', 'now')}")
    lines.append(f"# Path: {meta.get('path', 'unknown')}")
    lines.append(f"# Algorithm: {meta.get('algorithm', 'sha3_512')}")
    if meta.get("orientation"):
        lines.append(f"# Orientation: {meta['orientation']}")
    if meta.get("source"):
        lines.append(f"# Source: {meta['source']}")
    for i in range(0, len(b64), 64):
        lines.append(b64[i:i + 64])
    lines.append(f"-----END {label.upper()}-----")
    lines.append(f"# Checksum: {cs}")
    return "\n".join(lines)


def to_json(key: bytes, meta: Dict) -> str:
    """Format key as JSON with metadata."""
    out = {
        "key": base64.b64encode(key).decode(),
        "algorithm": meta.get("algorithm", "sha3_512"),
        "checksum": compute_checksum(key),
        "created_at": meta.get("created_at", datetime.now(timezone.utc).isoformat()),
        "path": meta.get("path", "m/44'/0'/0'"),
    }
    if meta.get("orientation"):
        out["orientation"] = meta["orientation"]
    if meta.get("source"):
        out["source"] = meta["source"]
    return json.dumps(out, separators=(",", ":"))


def to_binary(key: bytes) -> bytes:
    """Format key as a raw bytes blob with 4 byte big endian checksum prefix"""
    cs = struct.pack(">I", int(compute_checksum(key), 16) & 0xFFFFFFFF)
    return cs + key


def to_qr_ascii(data: str, size: int = 21) -> str:
    """Generate a 21x21 ASCII qr code like matrix from the hash data, unsure to implement it or not"""
    import hashlub
    h = hashlib.sha3_512(data.encode()).digest()
    grid = []
    for r in range(size):
        row = ""
        for c in range(size)