"""This is for exporting keys and metadata in multiple formats like PEM, JSON, JWK
, Binary, QR, SSH and PKCS8. ALL COMPLETELY SELF WRITTEN BTW"""
import base64
import json
import struct
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict
from . import ssh_format
from .key_derive import compute_checksum 
from .cli_output import log


def _encode_base64(data: bytes, urlsafe: bool = False) -> str:  
    if urlsafe:
        return base64.urlsafe_b64encode(data).decode().rstrip("=")
    return base64.b64encode(data).decode()


def to_pem(key: bytes, label: str, meta: Dict) -> str:
    b64 = _encode_base64(key)
    cs = compute_checksum(key)
    lines = [f"-----BEGIN {label.upper()}-----"]
    lines.append(f"# Generated by EntropyGarden on {meta.get('created_at', 'now')}")
    lines.append(f"# Path: {meta.get('path', 'unknown')}")
    lines.append(f"# Algorithm: {meta.get('algorithm', 'sha3_512')}")
    if meta.get("orientation"):
        lines.append(f"# Orientation: {meta['orientation']}")
    if meta.get("source"):
        lines.append(f"# Source: {meta['source']}")
    for i in range(0, len(b64), 64):
        lines.append(b64[i:i+64])
    lines.append(f"-----END {label.upper()}-----")
    lines.append(f"# Checksum: {cs}")
    return "\n".join(lines)


def to_json(key: bytes, meta: Dict) -> str:
    out = {
        "key": _encode_base64(key),
        "algorithm": meta.get("algorithm", "sha3_512"),
        "checksum": compute_checksum(key),
        "created_at": meta.get("created_at", datetime.now(timezone.utc).isoformat()),
        "path": meta.get("path", "m/44'/0'/0'"),
    }
    if meta.get("orientation"):
        out["orientation"] = meta["orientation"]
    if meta.get("source"):
        out["source"] = meta["source"]
    return json.dumps(out, separators=(",", ":"))


def to_binary(key: bytes) -> bytes:
    """Format key as a raw byte with idk 4 byte big endian checksum prefix"""
    cs = struct.pack(">I", int(compute_checksum(key), 16) & 0xFFFFFFFF)
    return cs + key


def to_qr_png(data: str) -> bytes:
    try:
        import qrcode
    except ImportError:
        from . import qr
        return qr.encode_png(data.encode("utf-8"))
    
    qr_obj = qrcode.QRCode(
        version=None,  # Auto-select
        error_correction=qrcode.constants.ERROR_CORRECT_H,  # High error correction
        box_size=10,
        border=4,
    )
    qr_obj.add_data(data)
    qr_obj.make(fit=True)
    

    img = qr_obj.make_image(fill_color="black", back_color="white")
    
    import io
    png_bytes = io.BytesIO()
    img.save(png_bytes, format="PNG")
    return png_bytes.getvalue()


def to_qr_ascii(data: str, size: int =21) -> str:
    from . import qr
    return qr.encode(data.encode("utf-8"))


def to_jwk(key: bytes, meta: Dict) -> str:
    k_b64 = _encode_base64(key, urlsafe=True)
    jwk = {
        "kty": "oct",
        "k": k_b64,
        "alg": meta.get("jwk_alg", "HS512"),
        "key_ops": ["sign", "verify"],
        "ext": True,
    }
    if meta.get("path"):
        jwk["path"] = meta["path"]
    if meta.get("source"):
        jwk["source"] = meta["source"]
    if meta.get("orientation"):
        jwk["orientation"] = meta["orientation"]
    jwk["checksum"] = compute_checksum(key)
    return json.dumps(jwk, indent=2)


def write_key(key: bytes, path: str, fmt: str, meta: Dict) -> None:
    p = Path(path).expanduser()
    p.parent.mkdir(parents=True, exist_ok=True)
    try:
        if fmt == "pem":
            content = to_pem(key, "PRIVATE KEY", meta)
            p.write_text(content, encoding="utf-8")
        elif fmt =="json":
            content = to_json(key, meta)
            p.write_text(content, encoding="utf-8")
        elif fmt == "jwk":
            content = to_jwk(key, meta)
            p.write_text(content, encoding="utf-8")
        elif fmt == "ssh":
            content = ssh_format.to_ssh_public_key(key, meta.get("comment", ""))
            if not p.name.endswith(".pub"):
                p = p.with_name(p.stem + ".pub")
            p.write_text(content + "\n", encoding="utf-8")
        elif fmt == "binary":
            p.write_bytes(to_binary(key))
        elif fmt == "qr" or fmt == "qr-ascii":
            # ASCII art QR code (text-based, for archival)
            key_b64 = _encode_base64(key)
            content = to_qr_ascii(key_b64)
            # Use .qr.txt extension for ASCII QR
            if not p.name.endswith(".qr.txt"):
                p = p.with_name(p.stem + ".qr.txt")
            p.write_text(content, encoding="utf-8")
        elif fmt == "qr-png":
            # PNG QR code (image, mobile-scannable)
            key_b64 = base64.b64encode(key).decode()
            png_bytes = to_qr_png(key_b64)
            # Use .qr.png extension for PNG QR
            if not p.name.endswith(".qr.png"):
                p = p.with_name(p.stem + ".qr.png")
            p.write_bytes(png_bytes)
        else:
            raise ValueError(f"Unknown format: {fmt}")
        log(f"Exported {fmt} to {p}")
    except PermissionError as e:
        from .cli_output import error_msg
        error_msg(f"Permission dened: {e}")
        raise SystemExit(1)
    


def write_ed25519_keypair(seed: bytes, path_priv: str, path_pub: str,
                          meta: Dict) -> None:
    from . import ed25519
    sk = ed25519.Ed25519SigningKey(seed)
    pk_bytes = sk.public_key
    priv_pem = ssh_format.to_pkcs8_pem(seed, pk_bytes)
    Path(path_priv).write_text(priv_pem + "\n", encoding="utf-8")
    ssh_pub = ssh_format.to_ssh_public_key(pk_bytes, meta.get("source", ""))
    Path(path_pub).write_text(ssh_pub + "\n", encoding="utf-8")
    pub_pem = ssh_format.to_subject_public_key_info_pem(pk_bytes)
    pub_pem_path = path_pub.replace(".pub", "_pem.pub")
    if pub_pem_path == path_pub:
        pub_pem_path = path_pub + ".pem"
    Path(pub_pem_path).write_text(pub_pem + "\n", encoding="utf-8")
    
    log(f"Exported Ed25519 private key to {path_priv}")
    log(f"Exported Ed25519 public key to {path_pub}")
    
    
def write_x25519_keypair(seed: bytes, path_priv: str, path_pub: str,
                         meta: Dict) -> None:
    from . import x25519
    pub_bytes = x25519.generate_public_key(seed)
    
    priv_out = {
        "kty" : "OKP",
        "crv" : "X25519",
        "d" : base64.urlsafe_b64encode(seed).decode().rstrip("="),
        "x" : base64.urlsafe_b64encode(pub_bytes).decode().rstrip("="),
    }
    priv_out.update(meta)
    
    pub_out = {
        "kty" : "OKP",
        "crv" : "X25519",
        "x": base64.urlsafe_b64encode(pub_bytes).decode().rstrip("="),
    }
    
    Path(path_priv).write_text(json.dumps(priv_out, indent=2), encoding="utf-8")
    Path(path_pub).write_text(json.dumps(pub_out, indent=2), encoding="utf-8")
    log(f"Exported X25519 private key to {path_priv}")
    log(f"Exported X25519 public key to {path_pub}")
